# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

include:
  - project: dhei/teams/pandora/gitlab-ci-templates
    file: products/gocomponents/GoComponent.Pipeline.gitlab-ci.yml
    ref: develop

variables:
  TARGET_IMAGE_SUBGROUP: horizon

  HAZELCAST_HOST: docker
  HAZELCAST_IMAGE: dockerhub.devops.telekom.de/hazelcast/hazelcast
  HAZELCAST_TAG: 5.3.6

  MONGO_HOST: docker
  MONGO_IMAGE: dockerhub.devops.telekom.de/mongo
  MONGO_TAG: 7.0.5-rc0

test:
  variables:
    GO_TEST_TAGS: "testing,musl"
    GO_TEST_PARALLEL: 1
    ADD_PACKAGES: "gcc pkgconf libc-dev musl-dev librdkafka-dev"
    CGO_ENABLED: 1
