# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

include:
  - project: dhei/teams/pandora/gitlab-ci-templates
    file: products/gocomponents/GoComponent.Pipeline.gitlab-ci.yml
    ref: chore/push-to-artifactory

variables:
  TARGET_IMAGE_SUBGROUP: horizon
  GO_BUILD_BASE_IMAGE: trusted.artifactory.devops.telekom.de/hub.docker.com/library/golang:1.26-alpine

  HAZELCAST_HOST: docker
  HAZELCAST_IMAGE: trusted.artifactory.devops.telekom.de/hub.docker.com/hazelcast/hazelcast
  HAZELCAST_TAG: 5.3.6

  MONGO_HOST: docker
  MONGO_IMAGE: trusted.artifactory.devops.telekom.de/hub.docker.com/library/mongo
  MONGO_TAG: 7.0.5-rc0

test:
  variables:
    GO_TEST_TAGS: testing
    GO_TEST_PARALLEL: 1